# ML Assignment 02
### Dataset: House Price Prediction Dataset
### Total Marks: 100

---

## Exam Instructions:
1. প্রথমে নিচের cell এ নিজের **নাম** এবং কোর্সে registration করা **ইমেইল** দিবে
2. Question wise numbering করে Text cell রাখবে এবং এর নিচে Code cell থাকবে, চেষ্টা করবে একটি code cell এ একটি question উত্তর দেওয়ার
3. Google Colab এর মধ্যে কোডগুলো করবে
4. এবং সেই ফাইলটি **'Anyone with the link' & 'View' Access** দিয়ে ফাইলটির Shareable Link টি সাবমিট করবে

---

**Question Dataset Link:** https://www.kaggle.com/datasets/prokshitha/home-value-insights

## Student Information

In [ ]:
# Fill in your information
name = "Sheikh Mohammed Sayed Ali"                 # Write your full name here
email = "sheikhmohamedsayedali@gmail.com"          # Write your registered email here

print(f"Name  : {name}")
print(f"Email : {email}")

Name  : Sheikh Mohammed Sayed Ali
Email : sheikhmohamedsayedali@gmail.com

---
## Question 1 (10 Marks)

Load the House Price dataset and display:
- Dataset shape
- First 10 rows
- 5 random samples

In [ ]:
# Question 1
import numpy as np
import pandas as pd
from sklearn.impute import SimpleImputer
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline


df=pd.read_csv('house_price_regression_dataset.csv')
print(df.shape)
print(df.head(10))
print(df.sample(5))

(1000, 8)
   Square_Footage  Num_Bedrooms  Num_Bathrooms  Year_Built  Lot_Size  \
0            1360             2              1        1981  0.599637
1            4272             3              3        2016  4.753014
2            3592             1              2        2016  3.634823
3             966             1              2        1977  2.730667
4            4926             2              1        1993  4.699073
5            3944             5              3        1990  2.475930
6            3671             1              2        2012  4.911960
7            3419             1              1        1972  2.805281
8             630             3              3        1997  1.014286
9            2185             4              2        1981  3.941604

   Garage_Size  Neighborhood_Quality   House_Price
0            0                     5  2.623829e+05
1            1                     6  9.852609e+05
2            0                     9  7.779774e+05
3            1                     8  2.296989e+05
4            0                     8  1.041741e+06
5            2                     8  8.797970e+05
6            0                     1  8.144279e+05
7            1                     1  7.034131e+05
8            1                     8  1.738750e+05
9            2                     5  5.041765e+05
     Square_Footage  Num_Bedrooms  Num_Bathrooms  Year_Built  Lot_Size  \
241            2985             3              2        2006  4.620525
262            1199             1              1        1953  2.459271
588            1173             3              1        1973  3.556396
770            4527             4              2        1951  1.000117
175            1159             1              2        1957  2.802361

     Garage_Size  Neighborhood_Quality    House_Price
241            2                     5  717150.442130
262            0                     2  211038.853163
588            1                     6  288382.460461
770            0                     7  898403.537212
175            2                     3  250101.547331

---
## Question 2 (10 Marks)

Handle missing values and perform feature engineering:
- Impute missing numerical values using `SimpleImputer` with mean strategy
- Impute missing categorical values using most frequent strategy
- Drop columns with more than 50% missing values
- Perform train-test split with `test_size=0.2` and `random_state=42`

Display the shape of final train and test sets.

In [ ]:
#Question 2

df.isnull().sum()
num_col=df.select_dtypes(include=["int64","float64"]).columns

num_imputer=SimpleImputer(strategy="mean")
df[num_col]=num_imputer.fit_transform(df[num_col])
df[num_col]

,Square_Footage,Num_Bedrooms,Num_Bathrooms,Year_Built,Lot_Size,Garage_Size,Neighborhood_Quality,House_Price
0,1360.0,2.0,1.0,1981.0,0.599637,0.0,5.0,2.623829e+05
1,4272.0,3.0,3.0,2016.0,4.753014,1.0,6.0,9.852609e+05
2,3592.0,1.0,2.0,2016.0,3.634823,0.0,9.0,7.779774e+05
3,966.0,1.0,2.0,1977.0,2.730667,1.0,8.0,2.296989e+05
4,4926.0,2.0,1.0,1993.0,4.699073,0.0,8.0,1.041741e+06
...,...,...,...,...,...,...,...,...
995,3261.0,4.0,1.0,1978.0,2.165110,2.0,10.0,7.014940e+05
996,3179.0,1.0,2.0,1999.0,2.977123,1.0,10.0,6.837232e+05
997,2606.0,4.0,2.0,1962.0,4.055067,0.0,2.0,5.720240e+05
998,4723.0,5.0,2.0,1950.0,1.930921,0.0,7.0,9.648653e+05
999,3268.0,4.0,2.0,1983.0,3.108790,2.0,2.0,7.425993e+05

In [ ]:
cat_col=df.select_dtypes(include=["object"]).columns
cat_col
cat_imputer=SimpleImputer(strategy="most_frequent")
df[cat_col]=cat_imputer.fit_transform(df[cat_col])
df[cat_col]    # akane kono cat col nai vaiya

ValueError: at least one array or dtype is required

In [ ]:
df.isnull().sum()

Square_Footage          0
Num_Bedrooms            0
Num_Bathrooms           0
Year_Built              0
Lot_Size                0
Garage_Size             0
Neighborhood_Quality    0
House_Price             0
dtype: int64

The dataset contains no missing values. Therefore, no columns were dropped for having more than 50% missing data, and applying SimpleImputer did not change the dataset.

In [ ]:
df

,Square_Footage,Num_Bedrooms,Num_Bathrooms,Year_Built,Lot_Size,Garage_Size,Neighborhood_Quality,House_Price
0,1360.0,2.0,1.0,1981.0,0.599637,0.0,5.0,2.623829e+05
1,4272.0,3.0,3.0,2016.0,4.753014,1.0,6.0,9.852609e+05
2,3592.0,1.0,2.0,2016.0,3.634823,0.0,9.0,7.779774e+05
3,966.0,1.0,2.0,1977.0,2.730667,1.0,8.0,2.296989e+05
4,4926.0,2.0,1.0,1993.0,4.699073,0.0,8.0,1.041741e+06
...,...,...,...,...,...,...,...,...
995,3261.0,4.0,1.0,1978.0,2.165110,2.0,10.0,7.014940e+05
996,3179.0,1.0,2.0,1999.0,2.977123,1.0,10.0,6.837232e+05
997,2606.0,4.0,2.0,1962.0,4.055067,0.0,2.0,5.720240e+05
998,4723.0,5.0,2.0,1950.0,1.930921,0.0,7.0,9.648653e+05
999,3268.0,4.0,2.0,1983.0,3.108790,2.0,2.0,7.425993e+05

In [ ]:
x=df.drop("House_Price",axis=1)
y=df["House_Price"]

x_train,x_test,y_train,y_test=train_test_split(
    x,y,test_size=0.2,random_state=42)



print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(800, 7)
(200, 7)
(800,)
(200,)

---
## Question 3 (20 Marks)

Implement **Simple Linear Regression** using **only NumPy** (no Scikit-Learn allowed):
- Compute slope (`m`) and intercept (`c`) using the Batch Gradient Descent
- Predict values for the test set
- Print the learned `m` and `c` values

Use `Square_Footage` as feature (X) and `House_Price` as target (y).

In [ ]:
#Question 3
x=df["Square_Footage"].values
y=df["House_Price"].values
x_train,x_test,y_train,y_test=train_test_split(
    x,y,test_size=0.2,random_state=42)


def compute_cost(x,y,W,b):
    m=x.shape[0]
    cost=0
    for i in range(m):
        pred_y=W*x[i]+b

        error =  pred_y - y[i]

        cost = cost + error**2

    return cost / (2 * m)

def gradient(x,y,W,b):
  m=x.shape[0]
  dj_dw=0
  dj_db=0

  for i in range(m):
    pred_y= W*x[i]+b

    error = pred_y - y[i]
    dj_dw = dj_dw +(error*x[i])
    dj_db = dj_db + error

  return dj_dw / m, dj_db / m

def gradient_descent(x,y,w_input,b_input,alpha,num_iters):
    W = w_input
    b = b_input

    cost_memo = []
    iteration = []


    for i in range(num_iters):

      dj_dw,dj_db=gradient(x,y,W,b)

      W=W-alpha*dj_dw

      b=b-alpha*dj_db

      cost=compute_cost(x,y,W,b)
      cost_memo.append(cost)
      iteration.append(i)
      if i % 100 == 0:
        print(f"Iteration {i}: Cost = {cost:.4f}, w = {W:.4f}, b = {b:.4f}")




    return W,b,cost_memo,iteration

w_final,b_final,cost_memo,iteration=gradient_descent(x_train,y_train,w_input=0,
    b_input=0,
    num_iters=1000,
    alpha=0.0000000001
)


for i in range(len(x_test)):

  pred_y=w_final*x_test[i]+b_final
   # x _test final weight gola use kore prediction
  print("Actual:", y_test[i], " Predicted:", pred_y)

print("\nSlope (m) =", w_final)
print("Intercept (c) =", b_final)

Iteration 0: Cost = 222983803796.5385, w = 0.2055, b = 0.0001
Iteration 100: Cost = 184574774567.4608, w = 19.8010, b = 0.0060
Iteration 200: Cost = 152805727750.9816, w = 37.6224, b = 0.0113
Iteration 300: Cost = 126528772673.3334, w = 53.8304, b = 0.0162
Iteration 400: Cost = 104794460903.0682, w = 68.5709, b = 0.0207
Iteration 500: Cost = 86817480437.4156, w = 81.9769, b = 0.0248
Iteration 600: Cost = 71948280525.3618, w = 94.1691, b = 0.0285
Iteration 700: Cost = 59649601865.3117, w = 105.2575, b = 0.0319
Iteration 800: Cost = 49477064157.9598, w = 115.3420, b = 0.0349
Iteration 900: Cost = 41063109596.8140, w = 124.5135, b = 0.0377
Actual: 901000.4882338208  Predicted: 532693.8798852386
Actual: 494537.5115454976  Predicted: 306710.600971749
Actual: 949404.2006657254  Predicted: 625105.3734949853
Actual: 1040389.0481357794  Predicted: 654847.0036222601
Actual: 794010.0167336396  Predicted: 484098.1806594236
Actual: 724033.5604571347  Predicted: 476131.67258961784
Actual: 998439.2371139774  Predicted: 615811.1140802118
Actual: 909713.435000704  Predicted: 547963.0203523663
Actual: 792681.5184200833  Predicted: 502022.8238164865
Actual: 947490.777477816  Predicted: 563364.9359539907
Actual: 774150.0468123948  Predicted: 479318.2758175401
Actual: 654466.9454086807  Predicted: 407354.1529202949
Actual: 217462.4450570884  Predicted: 103564.64519170245
Actual: 1034380.2041616676  Predicted: 653917.5776807826
Actual: 530476.1232749791  Predicted: 340568.2602684234
Actual: 194353.7361399757  Predicted: 117506.0343138625
Actual: 441315.08847493527  Predicted: 290246.48429415043
Actual: 354744.6305953098  Predicted: 226381.6446012077
Actual: 755402.3726912518  Predicted: 442406.78842744016
Actual: 348893.55395287194  Predicted: 182698.62535177288
Actual: 763645.6101593996  Predicted: 458870.9051050387
Actual: 475767.3504503976  Predicted: 304586.1988198008
Actual: 676108.8512096877  Predicted: 440282.38627549197
Actual: 887527.9071799915  Predicted: 549290.7716973339
Actual: 438250.1761546225  Predicted: 258247.6768804307
Actual: 402213.42189319455  Predicted: 193055.08584252032
Actual: 472657.61431723344  Predicted: 263425.9071258044
Actual: 453579.1055342158  Predicted: 253467.77203854723
Actual: 191907.6525048871  Predicted: 121754.83861775891
Actual: 489595.4124613424  Predicted: 263027.5817223141
Actual: 270230.63769827964  Predicted: 143397.18554073118
Actual: 893926.6294720689  Predicted: 566020.4386439259
Actual: 771922.849821314  Predicted: 468829.0401922959
Actual: 338350.5954344411  Predicted: 185088.57777271458
Actual: 457643.0980423783  Predicted: 282943.8518968285
Actual: 775773.2237663032  Predicted: 479052.7255485466
Actual: 474659.86005527806  Predicted: 279226.14813091914
Actual: 570399.7427677898  Predicted: 342692.6624203716
Actual: 280961.6803897855  Predicted: 129323.02128407436
Actual: 147601.55157708153  Predicted: 87764.40418658772
Actual: 300656.0790681994  Predicted: 176590.9691649218
Actual: 307101.6858385633  Predicted: 133040.7250499837
Actual: 486872.0567091347  Predicted: 294096.96319455653
Actual: 304653.63604893  Predicted: 169155.5616331031
Actual: 1092026.89678641  Predicted: 663211.8370955561
Actual: 1008539.156234348  Predicted: 579297.9520936022
Actual: 747938.7115439639  Predicted: 492861.3395362099
Actual: 818613.7108034128  Predicted: 501624.49841299624
Actual: 1028282.3118218936  Predicted: 620192.693518605
Actual: 694917.3008745462  Predicted: 450240.52136274916
Actual: 261227.3187203414  Predicted: 134102.9261259578
Actual: 762769.5055574658  Predicted: 446257.2673278463
Actual: 813296.8090259811  Predicted: 487284.78388734587
Actual: 705754.4319783618  Predicted: 428067.07390178984
Actual: 530824.1967752124  Predicted: 306179.5004337619
Actual: 809686.201143527  Predicted: 491533.5881912423
Actual: 190828.13988469375  Predicted: 84577.80095866542
Actual: 335332.59275293903  Predicted: 168491.68596061927
Actual: 728289.8873118911  Predicted: 447319.4684038204
Actual: 217213.6452196605  Predicted: 122020.38888675244
Actual: 993273.0796606252  Predicted: 612757.2859867864
Actual: 377511.26849809097  Predicted: 201951.01985380342
Actual: 322312.8625079516  Predicted: 137953.40502636394
Actual: 517515.4060050993  Predicted: 285201.02918327344
Actual: 604936.830452781  Predicted: 348136.4429347389
Actual: 551324.4886576998  Predicted: 352916.3477766223
Actual: 468699.4412955908  Predicted: 235808.67915047784
Actual: 729494.9061684583  Predicted: 456082.6272806067
Actual: 951093.5469938468  Predicted: 596558.7195781813
Actual: 746167.7281082802  Predicted: 435369.7062991118
Actual: 480961.44203831744  Predicted: 289184.28321817634
Actual: 875981.0268954616  Predicted: 534021.6312302062
Actual: 264215.33977452776  Predicted: 168624.46109511604
Actual: 574912.7662317117  Predicted: 338311.0829819784
Actual: 684425.2003263966  Predicted: 392350.5627221608
Actual: 733612.8163648158  Predicted: 438954.63493052433
Actual: 551444.6316158974  Predicted: 299142.41830543353
Actual: 188531.42345710637  Predicted: 98386.41494632872
Actual: 537619.5908056167  Predicted: 353845.77371809963
Actual: 872676.434152397  Predicted: 562435.5100125134
Actual: 545482.7420093057  Predicted: 341896.01161339105
Actual: 397346.1108776756  Predicted: 201287.1441813196
Actual: 534533.0200368982  Predicted: 317996.48740397376
Actual: 191117.1012230497  Predicted: 111132.82785801792
Actual: 149743.4999535613  Predicted: 66918.70807059603
Actual: 379005.7118671184  Predicted: 189071.83180761745
Actual: 964865.2986386952  Predicted: 627097.0005124366
Actual: 935451.9335719376  Predicted: 533357.7555577224
Actual: 552158.5008426193  Predicted: 288520.4075456925
Actual: 224507.20014868543  Predicted: 82187.8485377237
Actual: 934919.3827777772  Predicted: 563763.261357481
Actual: 781388.9356850483  Predicted: 494189.0908811775
Actual: 364834.6821527956  Predicted: 233153.1764605426
Actual: 798362.7750475319  Predicted: 459534.78077752254
Actual: 706686.3209428937  Predicted: 451169.9473042265
Actual: 1068538.1056038716  Predicted: 662813.5116920657
Actual: 760720.1464642045  Predicted: 459136.45537403226
Actual: 898283.8867356428  Predicted: 550352.9727733079
Actual: 863289.3969030941  Predicted: 510122.107020789
Actual: 605369.8615424815  Predicted: 376550.321717046
Actual: 917235.4105319374  Predicted: 562302.7348780166
Actual: 871566.5627396672  Predicted: 531897.229078258
Actual: 262707.27893308154  Predicted: 104228.52086418627
Actual: 605143.9591154716  Predicted: 375355.34550657513
Actual: 470083.2903669343  Predicted: 294628.0637325436
Actual: 913774.3890331694  Predicted: 618201.0665011536
Actual: 560304.6612210645  Predicted: 310428.3047376583
Actual: 198773.4757127592  Predicted: 109805.07651305028
Actual: 285546.501684919  Predicted: 147114.88930664054
Actual: 1037911.6519852468  Predicted: 629752.5032023719
Actual: 827140.4447152761  Predicted: 508528.8054068279
Actual: 418003.15725851554  Predicted: 215095.7581689829
Actual: 933332.7201261588  Predicted: 543581.4409139731
Actual: 533656.3940212176  Predicted: 336585.0062335205
Actual: 730047.4973881331  Predicted: 478521.62501055957
Actual: 914555.7450033636  Predicted: 591114.939063814
Actual: 294558.07202157495  Predicted: 131181.87316702903
Actual: 882532.5489330415  Predicted: 556991.7294981461
Actual: 252024.0176812598  Predicted: 113788.33054795316
Actual: 724814.2264216079  Predicted: 458074.25429805816
Actual: 246717.9663664509  Predicted: 93075.40956645823
Actual: 481489.24616078194  Predicted: 290379.2594286472
Actual: 889364.8170683798  Predicted: 520611.34264603327
Actual: 219426.92448759967  Predicted: 146849.339037647
Actual: 338170.31528112484  Predicted: 205137.6230817257
Actual: 327253.4579829949  Predicted: 201154.36904682283
Actual: 548288.2433774915  Predicted: 308436.6777202069
Actual: 848697.2899849606  Predicted: 541324.2636275281
Actual: 953339.7306451156  Predicted: 581024.0288420601
Actual: 574383.5478606392  Predicted: 357165.1520805187
Actual: 779336.1178319983  Predicted: 440016.83600649843
Actual: 685644.2336178538  Predicted: 411204.631820701
Actual: 619660.8346800937  Predicted: 371770.41687516257
Actual: 701493.9970692651  Predicted: 432979.75387817004
Actual: 673586.747670695  Predicted: 425278.79607735784
Actual: 866877.3524150968  Predicted: 525922.3480259037
Actual: 513720.44181706064  Predicted: 329415.1489706953
Actual: 624112.1600204634  Predicted: 405893.6264408305
Actual: 652166.1423658864  Predicted: 429394.8252467575
Actual: 248224.0196560961  Predicted: 131712.97370501608
Actual: 485380.95019563066  Predicted: 262629.25631882384
Actual: 861356.9775590366  Predicted: 480646.02716250776
Actual: 336153.4280264353  Predicted: 207527.57550266743
Actual: 749610.4677553453  Predicted: 465907.9872333671
Actual: 897176.5668201512  Predicted: 532030.0042127548
Actual: 343678.93524860224  Predicted: 194648.3874564815
Actual: 926094.1390762049  Predicted: 599878.0979406004
Actual: 370992.4565584571  Predicted: 193718.96151500414
Actual: 697909.6503581115  Predicted: 411204.631820701
Actual: 915441.1797542056  Predicted: 616342.2146181989
Actual: 583183.4309103092  Predicted: 327821.8473567342
Actual: 788150.9318106314  Predicted: 498570.6703195707
Actual: 931856.9695152728  Predicted: 629619.7280678751
Actual: 901471.7427249742  Predicted: 566418.7640474163
Actual: 1033816.8247013512  Predicted: 635860.159389223
Actual: 697780.778011206  Predicted: 403503.6740198888
Actual: 269061.7820440072  Predicted: 142600.5347337506
Actual: 627322.941247679  Predicted: 419569.465293997
Actual: 986006.861736761  Predicted: 636922.3604651971
Actual: 754662.1768906609  Predicted: 468696.2650577991
Actual: 238459.1158908021  Predicted: 97589.76413934815
Actual: 870212.7996762642  Predicted: 554601.7770772044
Actual: 804727.9577270229  Predicted: 480247.7017590175
Actual: 665369.9589318279  Predicted: 410673.531282714
Actual: 1017583.4273609958  Predicted: 657369.7311776985
Actual: 972040.0599877926  Predicted: 613819.4870627604
Actual: 895675.5548211845  Predicted: 577173.549941654
Actual: 190802.0703078011  Predicted: 97191.43873585785
Actual: 644601.105174152  Predicted: 397130.4675640442
Actual: 867445.4184620865  Predicted: 499367.32112655125
Actual: 646766.2897519646  Predicted: 395537.16595008306
Actual: 246540.9659359964  Predicted: 134102.9261259578
Actual: 515813.7578353911  Predicted: 295026.3891360339
Actual: 460741.2339285246  Predicted: 272852.9416750746
Actual: 523323.0670600654  Predicted: 306710.600971749
Actual: 496427.1035646905  Predicted: 299673.51884342055
Actual: 611205.6889207754  Predicted: 406955.8275168046
Actual: 1038652.4247755758  Predicted: 634134.0826407651
Actual: 665969.5719032948  Predicted: 426473.7722878287
Actual: 522309.4058721854  Predicted: 319457.0138834382
Actual: 1017321.3952750646  Predicted: 633071.881564791
Actual: 745395.8553692064  Predicted: 502819.4746234671
Actual: 336073.5215992294  Predicted: 185221.35290721135
Actual: 418888.6616954587  Predicted: 251741.69529008932
Actual: 542247.1622628621  Predicted: 347339.79212775826
Actual: 492018.32279508375  Predicted: 264886.43360526883
Actual: 344363.2736819858  Predicted: 231427.0997120847
Actual: 605600.9507407207  Predicted: 341232.13594090723
Actual: 564747.6546436538  Predicted: 353314.6731801126
Actual: 321278.1795200379  Predicted: 186018.00371419193
Actual: 504682.30124801846  Predicted: 318793.1382109544
Actual: 503962.1877251642  Predicted: 312951.0322930968
Actual: 967780.6667222162  Predicted: 624308.7226880046
Actual: 918893.7439235622  Predicted: 609437.9076243673
Actual: 252963.3562076132  Predicted: 99979.71656028986
Actual: 824529.5721138918  Predicted: 500163.97193353187
Actual: 180393.6281134625  Predicted: 81789.52313423342
Actual: 965816.66811073  Predicted: 596293.1693091878
Actual: 433664.2275283448  Predicted: 246696.24017921236
Actual: 663904.9927177994  Predicted: 424216.59500138374

Slope (m) = 132.77513449676243
Intercept (c) = 0.040284227748360484

---
## Question 4 (10 Marks)

Build a **ColumnTransformer** that applies:
- `StandardScaler` on numerical columns: `Square_Footage`, `Num_Bedrooms`, `Num_Bathrooms`
- `OneHotEncoder` on categorical column: `Neighborhood_Quality`

In [ ]:
#Question 4

num_col=["Square_Footage","Num_Bedrooms","Num_Bathrooms"]
cat_col=["Neighborhood_Quality"]
prepocessor=ColumnTransformer(
    transformers=[
        ("num",StandardScaler(),num_col),
        ("cat",OneHotEncoder(),cat_col)
    ]
)

prepocessor

ColumnTransformer(transformers=[('num', StandardScaler(),
                                 ['Square_Footage', 'Num_Bedrooms',
                                  'Num_Bathrooms']),
                                ('cat', OneHotEncoder(),
                                 ['Neighborhood_Quality'])])

## Question 5 (20 Marks)

Build a complete **Pipeline** using Scikit-Learn that includes:
- The `ColumnTransformer`
- `SGDRegressor` as the final estimator
- Train the pipeline and evaluate using RMSE and R² score
- Print predicted vs actual values for the first 10 test samples

In [ ]:
from sklearn.linear_model import SGDRegressor
from sklearn.pipeline import Pipeline
from sklearn.metrics import mean_squared_error, r2_score

x=df.drop("House_Price",axis=1)
y=df["House_Price"]

x_train,x_test,y_train,y_test=train_test_split(
    x,y,test_size=0.2,random_state=42)

ETA = 0.001
MAX_ITER =10000
ALPHA = 0.0001
sgd_pipeline=Pipeline(
    steps=[
        ('prepocessor',prepocessor),
        ('Modal2',SGDRegressor(eta0=ETA,max_iter=MAX_ITER,alpha=ALPHA))

    ]

)

sgd_pipeline.fit(x_train,y_train)
train_pred=sgd_pipeline.predict(x_train)
test_pred = sgd_pipeline.predict(x_test)

print("Train R2 Score:", r2_score(y_train, train_pred))
print("Test R2 Score:", r2_score(y_test, test_pred))
print("RMSE:", round(np.sqrt(mean_squared_error(y_test, test_pred)),4))

Train R2 Score: 0.9867652070311846
Test R2 Score: 0.9868698976258109
RMSE: 29092.1191

ভাই, SGDRegressor-কে একজন ছাত্র মনে করো।

```python
ETA = 0.001
MAX_ITER = 3000
ALPHA = 0.0001
```

এই ৩টা জিনিস ছাত্রটা **কীভাবে শিখবে** সেটা নিয়ন্ত্রণ করে।

---

## 1. ETA = 0.001

**ETA = Learning Rate**

এটা বলে:

> "একবারে কতটুকু শিখবি?"

ধরো তুমি সিঁড়ি দিয়ে নামছো।

* ETA বেশি → ৫টা ধাপ একসাথে লাফ দিবে 😅
* ETA কম → ১ ধাপ করে নামবে 🙂

```python
ETA = 0.001
```

মানে SGD আস্তে আস্তে weight update করবে।

Gradient Descent-এ:

```text
new_weight = old_weight - ETA × gradient
```

---

## 2. MAX_ITER = 3000

এটা বলে:

> "সর্বোচ্চ কতবার practice করতে পারবি?"

ধরো ছাত্রকে 3000 বার অনুশীলন করতে দেওয়া হয়েছে।

```python
MAX_ITER = 3000
```

মানে SGD সর্বোচ্চ 3000 বার weight update করবে।

Manual GD-তে যেমন:

```python
for i in range(3000):
```

একই ব্যাপার।

---

## 3. ALPHA = 0.0001

এটা বলে:

> "বেশি চালাকি করিস না, weight খুব বড় করিস না।"

ALPHA হলো **regularization**।

যদি model weight খুব বড় করতে শুরু করে:

```text
w1 = 50000
w2 = -80000
```

তাহলে ALPHA penalty দেয়।

ফলে model একটু simple থাকে এবং overfitting কমে।

---

## সবচেয়ে সহজ ভাষায়

| Parameter | কাজ                                     |
| --------- | --------------------------------------- |
| ETA       | কত দ্রুত শিখবে                          |
| MAX_ITER  | কতবার শিখবে                             |
| ALPHA     | overfitting কমাতে weight নিয়ন্ত্রণ করবে |

---

এক লাইনে মনে রাখো:

```text
ETA      → শেখার গতি
MAX_ITER → শেখার সময়/বার
ALPHA    → বেশি মুখস্থ করা আটকায়
```

SGDRegressor-এর performance অনেক সময় এই ৩টা hyperparameter-এর উপর নির্ভর করে।

#ETA (Learning Rate):
ETA model কত দ্রুত শিখবে তা নির্ধারণ করে। ছোট ETA হলে model ধীরে ধীরে weight update করে, আর বড় ETA হলে দ্রুত update করে।

#MAX_ITER:
MAX_ITER নির্ধারণ করে SGDRegressor সর্বোচ্চ কতবার weight update করবে। বেশি iteration হলে model শেখার জন্য বেশি সুযোগ পায়।

#$ALPHA:
ALPHA হলো regularization parameter। এটি weight খুব বড় হয়ে যাওয়া রোধ করে এবং overfitting কমাতে সাহায্য করে।

সংক্ষেপে:

ETA → শেখার গতি
MAX_ITER → কতবার শিখবে
ALPHA → Overfitting নিয়ন্ত্রণ করে এবং model-কে simpler রাখে।

In [ ]:
for i in range(10):
    print("Actual:", y_test.iloc[i], " Predicted:", test_pred[i])

Actual: 901000.4882338208  Predicted: 851516.1782016819
Actual: 494537.5115454976  Predicted: 507655.069514869
Actual: 949404.2006657254  Predicted: 986078.5128910029
Actual: 1040389.0481357794  Predicted: 1022699.8701504947
Actual: 794010.0167336396  Predicted: 760315.319887608
Actual: 724033.5604571347  Predicted: 765910.9413503426
Actual: 998439.2371139774  Predicted: 1004294.0584080974
Actual: 909713.435000704  Predicted: 903505.8810031393
Actual: 792681.5184200833  Predicted: 797587.3051791501
Actual: 947490.777477816  Predicted: 888919.0666119447

---
## Question 6 (20 Marks)

Implement **Multiple Linear Regression** using **Scikit-Learn**:
- The `ColumnTransformer`
- `LinearRegression` as the final estimator
- Train the pipeline and evaluate using RMSE and R² score
- Print predicted vs actual values for the first 10 test samples

In [ ]:
# Question 6
from sklearn.linear_model import LinearRegression
from sklearn.pipeline import Pipeline
from sklearn.metrics import mean_squared_error, r2_score

x=df.drop("House_Price",axis=1)
y=df["House_Price"]

x_train,x_test,y_train,y_test=train_test_split(
    x,y,test_size=0.2,random_state=42)



lr_pipeline=Pipeline(
    steps=[
        ("prepocessor",prepocessor),
        ("Modal1",LinearRegression())
    ]
)

lr_pipeline.fit(x_train,y_train)
train_pred=lr_pipeline.predict(x_train)
test_pred = lr_pipeline.predict(x_test)

from sklearn.metrics import root_mean_squared_error, r2_score

rmse = round(np.sqrt(mean_squared_error(y_test, test_pred)),4)

r2_test = r2_score(y_test,test_pred)

r2_train = r2_score(y_train, train_pred)

print("Train R2 Score:", r2_train)
print("Test R2 Score:", r2_test)
print("RMSE:", rmse)

Train R2 Score: 0.9867661768917739
Test R2 Score: 0.986869034559103
RMSE: 29093.0752

In [ ]:
for i in range(10):
    print("Actual:", y_test.iloc[i], " Predicted:", test_pred[i])

Actual: 901000.4882338208  Predicted: 851409.1473265477
Actual: 494537.5115454976  Predicted: 507641.0338696986
Actual: 949404.2006657254  Predicted: 985990.3750316359
Actual: 1040389.0481357794  Predicted: 1022654.7065338424
Actual: 794010.0167336396  Predicted: 760698.1336568068
Actual: 724033.5604571347  Predicted: 765782.3163809121
Actual: 998439.2371139774  Predicted: 1005039.0963438316
Actual: 909713.435000704  Predicted: 903407.781772362
Actual: 792681.5184200833  Predicted: 797971.1884095871
Actual: 947490.777477816  Predicted: 888850.4300376975

#**Q1. Which model has lower Test RMSE?**

LinearRegression has the lower Test RMSE compared to SGDRegressor. Therefore, LinearRegression performs slightly better on unseen test data.

#Q2. Is Train R² much higher than Test R²?

No. Train R² (0.5622) and Test R² (0.5464) are very close. Since the gap is small, the model does not show significant overfitting.

# Overfitting vs Underfitting

Overfitting occurs when a model performs very well on training data but poorly on test data. Underfitting occurs when a model performs poorly on both training and test data because it fails to learn the underlying pattern. In this case, the model appears reasonably balanced and does not show strong overfitting.

---
## Question 7 (10 Marks) (You have to explore the topic and use the equation via Numpy)
### Dont use LLMs , You can use Documentation

Implement **Multiple Linear Regression** using **only NumPy**:
- Pick random 100 datas from the dataset
- Use the Normal Equation: `θ = (XᵀX)⁻¹ Xᵀy`
- Use `Square_Footage`, `Num_Bedrooms`, and `Num_Bathrooms` as features
- Print the learned coefficients (θ values)

In [ ]:
# Question 7
df_sample=df.sample(100)
df_sample

,Square_Footage,Num_Bedrooms,Num_Bathrooms,Year_Built,Lot_Size,Garage_Size,Neighborhood_Quality,House_Price
328,1330.0,3.0,3.0,1962.0,2.618903,1.0,7.0,300656.079068
817,977.0,5.0,1.0,1956.0,1.795241,2.0,1.0,214146.491007
88,4145.0,3.0,1.0,1993.0,3.224353,1.0,7.0,898283.886736
619,3332.0,5.0,2.0,1962.0,1.751448,2.0,2.0,704212.523977
605,2650.0,2.0,1.0,2006.0,3.620008,0.0,7.0,596659.368549
...,...,...,...,...,...,...,...,...
777,3135.0,5.0,2.0,1988.0,0.703826,2.0,9.0,663727.544124
363,2257.0,3.0,1.0,2002.0,1.637593,2.0,10.0,496427.103565
730,617.0,1.0,1.0,1982.0,2.347231,0.0,5.0,147206.865763
801,1492.0,4.0,1.0,2014.0,2.433303,1.0,2.0,366271.845556
309,1074.0,4.0,2.0,1982.0,2.487859,1.0,9.0,269061.782044

In [ ]:
X = df_sample[
    ["Square_Footage",
     "Num_Bedrooms",
     "Num_Bathrooms"]
].values

y = df_sample["House_Price"].values

# pipline er concept er opor aroo video dila bhlo hoi ..course doc file gola open cara agola solve kora kotin hoi jacce...sob kico mokosto korsi bole mone hocce..R moneo takce na sob